/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TodoApp;

import Controller.ProjectsController;
import Model.Projects;
import java.sql.Connection;
import util.ConnectionFactory;

public class App {
    

    public static void main(String[] args) {
        
        
      /*Connection c =  ConnectionFactory.getConnection();
        
      ConnectionFactory.closeConnection(c);*/
        
        ProjectsController con = new ProjectsController();
         Projects project = new Projects();
         project.setName("nome");
         project.setDescription("descrip");
         System.out.println(project.getName() + " " + project.getDescription());
         con.save(project);
    }
}
